# Use lightweight OpenJDK image
FROM openjdk:21-jdk-slim

# Add a volume for temp files
VOLUME /tmp

# Copy the built JAR file into the container
COPY target/QRmaker-0.0.1-SNAPSHOT.jar app.jar

# Expose the port the app runs on
EXPOSE 8080

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app.jar"]
